### PR TITLE
#4 Refactored script to use data- attribute

### PR DESCRIPTION
**Pull request by chrisahardie**
Usage:
```
    <div data-percircle="17" class="c100 big">
         <span>17%</span>
         <div class="slice">
             <div class="bar"></div>
             <div class="fill"></div>
          </div>
     </div>
````

Still learning Github, be gentle :)

### CODE REVIEW

**Comment by toubou91** [comment]
Hey Chris,

no worries, you did a great job :+1: , but I believe, the implementation of <code>data-</code> attribute makes the id's current requirement (ending with "circle") redundant, so I foresee going only for the <code>data-</code> attribute.

Thus, we 'll then let the developer provide an div ids, only when he/she needs them.

I assigned this to me, as it is going to be part of the upcoming merge.

Thanks a lot!

**Comment by toubou91** [comment]
Hey Chris,

no worries :).

I suppose there's an issue with this implementation, as we have to assure a proper functionality for values, greater than 50%. Here is an example:

```html
<div data-percircle="77" class="c100 big">
	<span>77%</span>
	<div class="slice">
		<div class="bar"></div>
		<div class="fill"></div>
	</div>
</div>
```
image

What the above seems to need, in order to be rendered preperly, is the percentage class handling, which, to my understanding , after talking a glance at your code, is not implemented for <code>dataCircles</code>.

Secondly, the <code>data-</code> attribute implementation is pretty good, so it automatically makes the second (the one that provides an id ending with "circle") definition of a percircle object redundant. So, let's stick with the <code>data-</code> attribute and let the dev provide an id on a div, when he/she only needs to.

**Comment by chrisahardie** [comment]
Cool beans, I agree using a data attribute is a much better alternative. 
I'll keep an eye out for any future issues you open up to the floor.

Cheers,

C.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by toubou91** [comment]
(Hey, could you please post again your latest comment? Seems like my remote machine did a great job deleting it)

**Comment by chrisahardie** [comment]
@toubou91 I deleted it myself, it was no longer relevant. Updated the PR, IDs will no longer be used to target elements. Also resolved the issue where I wasn't applying the class, surprised I didn't notice that. Anyway, have a look and let me know if there was anything else in the context of this ticket.

**Comment by chrisahardie** [comment]
Stand by, I want to try another improvement, but for the life of me I don't know how to decline my own PR!

**Comment by toubou91** [comment]
Hey, no prob.

Just commit like you earlier did.
Since I haven't merged yet, every new change will be committed to the existing PR, too.

**Comment by chrisahardie** [comment]
Criminy, I'm trying to love this Atom editor, but the the formatting between the IDE and what gets displayed on Github is totally different.

Anyway, I removed a bunch of selectors, I don't believe they are needed. Please have a look and make sure I didn't miss anything.

**Comment by toubou91** [comment]
Seems to be ok now, thanks!

**Comment by toubou91** [comment]
Could you please provide this implementation as an alternative of the percircle() function? That is, let's give the user an alternative option of creating  <code>percircle</code> objects in the following format (adjusted to the current version of <b>percircle</b>):

```html
<div data-percircle="77" class="dark big"></div>
```

**Comment by chrisahardie** [comment]
Have you looked at my outstanding PR? If memory serves, data attributes can be used to create percircles, along with some cosmetic attributes.

**Comment by toubou91** [comment]
As I mentioned in the README, I currently don't have much spare time, but I will surely get into details of it, in the near future.

From a quick glance, I see that we still have to configure a percircle object from an inline script (either by declaring a specific series of ids or by direct jQuery configuration).

What I mean is to give an additional option to the user in order to be able to define percircle objects without even having to declaring ids or specific js configurations. For example, sth like this, that you configured in this PR, for a previous version of the project:

```html
<div data-percircle="77" class="dark big"></div>
```

**Comment by chrisahardie** [comment]
@toubou91 Not at all, but I believe that was already addressed in @chris--jones PR, though he did use 'dara-percent' attribute. (I'm on my phone and can't easily navigate the code changes)

Anyway, yes, we will ensure we can configure with data attributes, and we can rename to data-percircle easily enough. My outstanding PR  adds cosmetic styling through data attributes.

Good luck with the thesis!

**Pull request merged**
